set_property SRC_FILE_INFO {cfile:C:/Users/SET253-INS1U/Documents/GitHub/ENES246/11IP/2_Square_Root_IP/SquareRootIP.srcs/constrs_1/imports/ENES246/Nexys4DDR_Master.xdc rfile:../SquareRootIP.srcs/constrs_1/imports/ENES246/Nexys4DDR_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U11   IOSTANDARD LVCMOS33 } [get_ports { data_i[14] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=sw[14]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V10   IOSTANDARD LVCMOS33 } [get_ports { data_i[15] }]; #IO_L21P_T3_DQS_14 Sch=sw[15]
