# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_Labs/User_Demo/src/ip/Square_Root/Square_Root.xci
# IP: The module: 'Square_Root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Labs/User_Demo/src/ip/Square_Root/Square_Root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Square_Root'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Vivado_Labs/User_Demo/src/ip/Square_Root/Square_Root.xci
# IP: The module: 'Square_Root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Labs/User_Demo/src/ip/Square_Root/Square_Root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Square_Root'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
