# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen.xci
# IP: The module: 'PxlClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen.xci
# IP: The module: 'PxlClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PxlClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
