webtalk_init -webtalk_dir D:/GitHub/ENES-246/10Latches/1_SR_Latch/SR_Latch.sim/sim_1/behav/xsim/xsim.dir/SR_latch_dataflow_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 18 16:50:21 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1a006e1d-1543-4bee-a2d5-743fd4df0ef7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "583944a9137c4615b8ad0b68daee70f8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5144_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4102117512 -regid "" -xml D:/GitHub/ENES-246/10Latches/1_SR_Latch/SR_Latch.sim/sim_1/behav/xsim/xsim.dir/SR_latch_dataflow_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/GitHub/ENES-246/10Latches/1_SR_Latch/SR_Latch.sim/sim_1/behav/xsim/xsim.dir/SR_latch_dataflow_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/GitHub/ENES-246/10Latches/1_SR_Latch/SR_Latch.sim/sim_1/behav/xsim/xsim.dir/SR_latch_dataflow_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
