# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_Labs/User_Demo/proj/User_Demo.cache/wt [current_project]
set_property parent.project_path D:/Vivado_Labs/User_Demo/proj/User_Demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths d:/Vivado_Labs/User_Demo/repo [current_project]
set_property ip_output_repo d:/Vivado_Labs/User_Demo/proj/User_Demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet d:/Vivado_Labs/User_Demo/src/ip/BRAM_1/BRAM_1.dcp
set_property used_in_implementation false [get_files d:/Vivado_Labs/User_Demo/src/ip/BRAM_1/BRAM_1.dcp]
add_files -quiet d:/Vivado_Labs/User_Demo/src/ip/ClkGen/ClkGen.dcp
set_property used_in_implementation false [get_files d:/Vivado_Labs/User_Demo/src/ip/ClkGen/ClkGen.dcp]
add_files -quiet d:/Vivado_Labs/User_Demo/src/ip/ddr/ddr.dcp
set_property used_in_implementation false [get_files d:/Vivado_Labs/User_Demo/src/ip/ddr/ddr.dcp]
add_files -quiet d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen.dcp
set_property used_in_implementation false [get_files d:/Vivado_Labs/User_Demo/src/ip/PxlClkGen/PxlClkGen.dcp]
add_files -quiet d:/Vivado_Labs/User_Demo/src/ip/Square_Root/Square_Root.dcp
set_property used_in_implementation false [get_files d:/Vivado_Labs/User_Demo/src/ip/Square_Root/Square_Root.dcp]
read_vhdl -library xil_defaultlib {
  D:/Vivado_Labs/User_Demo/src/hdl/SPI_If.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/TWICtl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/TempDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/sSegDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/RgbLedDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/RamCntrl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/Ram2Ddr.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/Pwm.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/Ps2Interface.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/PdmSer.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/PdmDes.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/OverlayCtl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/MouseDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/MicDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/LogoDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/LocalRst.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/LedBar.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/Dbncr.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/ADXL362Ctrl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/AccelDisplay.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/AccelArithmetics.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/Vga.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/TempSensorCtl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/sSegDemo.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/RgbLed.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/MouseCtl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/FPGAMonitor.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/AudioDemo.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/AccelerometerCtl.vhd
  D:/Vivado_Labs/User_Demo/src/hdl/Nexys4DdrUserDemo.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado_Labs/User_Demo/src/constraints/Nexys4DDR_C.xdc
set_property used_in_implementation false [get_files D:/Vivado_Labs/User_Demo/src/constraints/Nexys4DDR_C.xdc]


synth_design -top Nexys4DdrUserDemo -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef Nexys4DdrUserDemo.dcp

catch { report_utilization -file Nexys4DdrUserDemo_utilization_synth.rpt -pb Nexys4DdrUserDemo_utilization_synth.pb }
